### ISSUE TITLE
Possibility of this becoming a Python library

### ISSUE THREAD

**Issue by charlieharris1** [awslabs/aws-greengrass-labs-iot-pubsub-sdk-for-python#1]
Hello 👋 , 

Thanks for all of your work on this, it's a really useful resource.

I was wondering if you've got any plans to turn this into a library, rather than making it available as a repo to clone/fork?

Thanks!

**Comment by dcolcott** [comment]
Hi Charlie,

Thanks for the feedback and the suggestion. To answer your question, yes; there is an intent to make this a library in the near future. I will update to this issue when we have made progress. It would be great to get your feedback once complete.

Regards,
Dean.

**Comment by charlieharris1** [comment]
Thanks for letting me know Dean. Sounds great and I'd be happy to provide feedback.

**Comment by dcolcott** [comment]
Hi Charlie, 
Its taken a while to come back to this but the AWS Greengrass PubSub framework is now available as a SDK / python library at: https://github.com/aws-samples/aws-greengrass-pubsub-sdk-for-python

**Comment by charlieharris1** [comment]
That's great news, thanks @dcolcott. We'll give it a whirl in the next few weeks.
