### ISSUE TITLE
Build a Distributed IoT Application with the AWS IoT Greengrass PubSub SDK Workshop points to old repo

### ISSUE THREAD

**Issue by dflatow** [awslabs/aws-greengrass-labs-iot-pubsub-sdk-for-python#2]
Looks like this tutorial (https://catalog.us-east-1.prod.workshops.aws/workshops/32dc1f13-985f-4f94-9b86-a859806d28f0/en-US)  is pointing to the old repo https://github.com/aws-samples/aws-greengrass-pubsub-sdk-for-python and needs to get updated to https://github.com/aws-samples/aws-greengrass-pubsub-sdk-for-python.

Specifically this line
```
git clone https://github.com/aws-samples/aws-greengrass-pubsub-sdk-for-python.git 
```
should be replaced with:
```
git clone https://github.com/awslabs/aws-greengrass-labs-iot-pubsub-sdk-for-python.git
```

**Comment by dflatow** [comment]
also some other commands need to be updated to point to new folder as well

**Comment by dcolcott** [comment]
Thanks David, I've made the updates. Just going through internal review and CR. Will publish the changes ASAP.

**Comment by dcolcott** [comment]
Update / Fix has been applied. 
Thanks for calling out.
